version: '3.5' 
services: 
  nexus_marven: 
    image: sonatype/nexus3:3.31.0 
    container_name: nexus_marven.3.31.0 
    restart: always 
    volumes: 
      - nexus-data:/nexus-data 
    ports: 
      - 18081:8081 
      - 18082:8082 
volumes: 
  nexus-data: 
    external: true 
